### PR TITLE
Poker game

### PR DESCRIPTION
**Pull request by meDracula**
This pull request will exit draft if all these issues are closed and clean up is complete!
- #8 
- #9 
- #10 
- #11 
- #12 
- BUG hunt:
  - #27 
- [x] Add reset game state
- [x] Clean up complete!
- [x] Package it!

### CODE REVIEW

**Comment by meDracula** [comment]
# CODE REVIEW TIME
Now take a deep look at the code and pull it apart. 
- Find bugs.
- Look for improvement.
- Look at what is missing?
> **DO NOT PRESS MERGE PULL REQUEST** unless all reviewers have given green light

**Review by Antonsen2 — APPROVED** [review]
Looks good, should not be any issues merging this into main.

**Comment by meDracula** [comment]
Last commit was for issue #23 
This should not alter differ as much from before the commit

**Review by marcoRanmna — COMMENTED** [review]
It looks good

**Review by MahboubehAzizzadeh — APPROVED** [review]

**Pull request merged**
